### ISSUE TITLE
Typo in 1.5.1 Using markdown in README files

### ISSUE THREAD

**Issue by mattmorana7** [LeDataSciFi/ledatascifi-2022#2]
@donbowen In the first bullet, in the second sentence, it reads, "You can that there is bolded and italics text, code, hyperlinks and headers for sectioning." It should include the word "see," so it reads, "You can **see** that there is bolded..."

Small fix, but wanted to bring it to your attention.

**Comment by donbowen** [comment]
Awesome find, thanks! Fixed, and noted in the participation log. 

(Btw, no need to, but you can directly submit typo fixes with the "suggest edit" button, which is right below the "open issue" button you clicked. You make the change and click through. I'd get a notice and just approve it.)
