### ISSUE TITLE
Issue on page /content/about/resources.html

### ISSUE THREAD

**Issue by mattmorana7** [LeDataSciFi/ledatascifi-2022#3]
@donbowen I would've suggested an edit here, but I'm not sure what the correct hyperlink should be in the Python dropdown, last bullet, which says [This has to be the best list of Python resources on the internet](https://github.com/EbookFoundation/free-programming-books/blob/main/free-programming-books.md#python). 

I feel that I'm starting to get a little lost/fall behind so I'm trying to utilize some of the resources you provided on the class website.

Thanks,
Matt

**Comment by donbowen** [comment]
Thanks for the pointer. They recently changed the link. I'll update it to this:

- [The best compilation of coding resources on the web](https://ebookfoundation.github.io/free-programming-books/), including:
  - [free python books](https://ebookfoundation.github.io/free-programming-books/books/free-programming-books-langs.html#python), 
  - [free interactive tutorials](https://ebookfoundation.github.io/free-programming-books/more/free-programming-interactive-tutorials-en.html#python), 
  - [free courses](https://ebookfoundation.github.io/free-programming-books/courses/free-courses-en.html#python)
  - [cheatsheets](https://ebookfoundation.github.io/free-programming-books/more/free-programming-cheatsheets.html#python)

If you use any of these and LIKE or DISLIKE them, please let me know so I can guide future students to resources.
